--
-- Name: tb_post; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_post (
    id bigint NOT NULL,
    body character varying(255),
    created_at timestamp without time zone,
    description character varying(255),
    title character varying(255),
    update_at timestamp without time zone
);


--
-- Name: tb_post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_post tb_post_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_post
    ADD CONSTRAINT tb_post_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

