spring:
## H2 DB
  datasource:
    url: jdbc:h2:mem:antimonitordb;MODE=Oracle
    driverClassName: org.h2.Driver
    username: sa
    password:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console