spring:
## H2 DB
#  datasource:
#    url: jdbc:h2:mem:antimonitordb;MODE=Oracle
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#    enabled: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

# ORACLE DB
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: oracle
    hikari:
      maximum-pool-size: 10

server:
  error:
    include-message: always